- lib/dat-worker-pool.rb
- lib/dat-worker-pool/worker.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/worker_tests.rb
This updates the hard shutdown logic to force worker threads down
using `Thread#raise`. This is not ideal but there isn't any other
way to force threads down if they are processing work. The hard
shutdown was and still is a "use at your own risk" feature. This
is slightly better handling because threads will be shutdown by
the raised exception and not by ruby (which uses `Thread#kill` and
is known to cause problems). It will also give error handling in
do work procs to have a chance to handle the error. This is part
of a set of changes to have better hard-shutdown logic to help
avoiding losing work.
> Update hard shutdown, raise shutdown error on threads

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/worker.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/worker_tests.rb
This updates workers to allow passing a proc for custom error
handling. This is needed because we are now using `Thread#raise`
to kill workers threads when forcing a worker pool to shutdown.
Since these exceptions can be raised at any point, we need to
allow systems to provide custom error handling when this occurs.
This expands a workers error catching to catch both standard errors
and hard shutdown errors for its entire loop. For hard shutdown
errors, after custom error handling is called, the worker will
reraise the error which ensures that thread will exit from the
exception.
This also fixes a small bug where it was possible that work
could be pulled off of the queue but could be shutdown before
processing it. This would result in the work being lost. Now if
work is pulled off, it …
> Add custom error handling to workers

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/queue.rb
- lib/dat-worker-pool/worker.rb
- test/unit/dat-worker-pool_tests.rb
This is a set of cleanups that doesn't change any functionality.
These changes are part of keeping the code easier to maintain and
understand. It has gone through a few rounds of fairly significant
changes so this seeks to cleanup the code that has been added and
changed.
It organizes methods so that they are more consistent.
Specifically, this moves the start/shutdown methods to the top for
the worker pool, queue and workers. This also simplifies some of
the comments explaining some of the more strange or confusing parts
of the code.
Finally, this simplifies the shutdown timeout handling. The
optional timeout has been simplified and the re-raise logic
removed. It now also raises a timeout error which then triggers
the worker pool to raise a shutdown error. This makes more sense
than the …
> Consistently organize methods, cleanup comments, simplify timeout

- lib/dat-worker-pool/worker_pool_spy.rb
- test/unit/worker_pool_spy_tests.rb
This updates the worker pool spy to have the same interface as the
real worker pool. This adds the on worker error callback methods
to it. This should've been done when they were added to the main
worker pool but was accidentally forgotten. This ensures the spy
is still a good stand-in for a real pool.
This also does some minor cleanups to the spy to keeps its methods
ordered similarly to the real pool. This should've also been done
when the real pools methods order was updated but it was also
forgotten.
@kellyredding - Ready for review. Noticed I forgot to update the spy when I brought it into Qs and tried to run the tests.
> Add on worker error callback to `WorkerPoolSpy`

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/worker.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/worker_tests.rb
This fixes a bug that was hidden by the test suite. Previously, the
worker pool, when forced to shutdown, would always raise a
`ShutdownError`. The tests hid this because they ran the worker
pool in debug mode, which is supposed to reraise the shutdown
error. The issue is if an exception is raised in a thread with
`Thread#raise` and its never rescued, it will be thrown when
joining the thread. This can cause the worker pool to not properly
shutdown all of its workers.
To fix this, the worker pool rescues any errors when joining its
threads and the worker will rescue the shutdown errors. The benefit
of having the worker rescue the shutdown error is it allows the
worker shutdown procs to be called. The worker pool needs to rescue
when joining the workers because its possible that the …
> Fix hard shutdown error always being raised by worker pool

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/worker_pool_spy.rb
- test/system/use_worker_pool_tests.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/worker_pool_spy_tests.rb
This changes worker pools to alway spawn a set number of workers.
They no longer have a min and max setting. This simplifies the
worker pools logic and is setup for allowing custom queue classes.
Previously, dat worker pool would allow specifying a min and max
number of workers. When work was added it would see if a worker
was available to process it, and if not, spawn another worker if
it hadn't reached the max. With allowing custom queue classes, this
option no longer makes as much sense. For some custom queue classes
they won't define a `push` method because they will not have work
directly pushed onto them. Instead they will get their work from
redis or a socket. In this case, there is no logical place to
trigger spawning additional workers. If we left min and max number
of workers …
> Remove min and max workers, always spawn a consistent number of workers

- lib/dat-worker-pool.rb
- test/helper.rb
- test/support/factory.rb
- test/system/use_worker_pool_tests.rb
- test/unit/dat-worker-pool_tests.rb
This fixes a rare but possible infinite loop bug when force
shutting down a worker pool.
Force shutting down raises shutdown errors in the worker pools
worker threads. This causes them to error and exit out. Its
possible that the worker thread is in a state when the shutdown
error is raised it doesn't catch it (the `ensure` block in its
`work_loop` method for example.). If this happens, the previous
logic would catch and ignore the error but wouldn't remove the
worker from its collection. Its `until` loop would iterate and
pick the same worker and infinitely repeat. This fixes it by
manually deleting the worker from the collection at the end of
the loop (when it normally shuts down it deletes itself from the
collection).
This also adds tests for this behavior and changes the forced …
> Fix infinite loop bug when force shutting down

- lib/dat-worker-pool.rb
- test/helper.rb
- test/system/use_worker_pool_tests.rb
- test/unit/dat-worker-pool_tests.rb
This updates `DatWorkerPool` to be initialized with an options
hash. This is better than a list of ordered arguments because its
more flexibile and can expand in the future. This is also setup
for allowing a queue and worker class to be passed when its
initialized. For now, the do work proc is being passed, which is
not the best interface but this will be changed once a worker
class can be passed.
This also changes the worker pool to not take a debug flag but
instead take a logger. This provides more flexibility for logging
and doesn't force only logging to stdout. The default is a null
logger which is a no-op (the methods do nothing) instead of using
`/dev/null` (because this isn't compatible on all systems).
This also adds validation for the number of workers to ensure it
is valid. This …
> Update `DatWorkerPool` to be initialized with options hash

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/default_queue.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/default_queue_tests.rb
- test/unit/worker_tests.rb
This renames the `Queue` class to `DefaultQueue`. This is setup for
having a base `Queue` mixin that can be used to define custom
queues for dat worker pool. This renames the existing queue as
a first step so the `Queue` name is now available. The
`DefaultQueue` will continue to be provided by dat worker pool and
will also continue to be the default for a worker pool.
@kellyredding - Ready for review. This will make the PR where I add a `Queue` mixin easier to read. Otherwise git will diff the memory queue logic with the queue mixin logic.
> Rename `Queue` to `DefaultQueue` 

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/default_queue.rb
- lib/dat-worker-pool/queue.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/default_queue_tests.rb
- test/unit/queue_tests.rb
- test/unit/worker_tests.rb
This adds a `Queue` mixin which defines the interface needed to
define a custom queue for dat-worker-pool. This also updates the
`DefaultQueue` to use it.
The `Queue` mixin defines the interface that dat-worker-pool
expects its queues to have. It is intended to be mixed into a
queue class and have its `!` methods overwritten. It provides some
default logic for handling starting and shutting down the queue
but doesn't provide any "queue" logic. A custom queue class is
responsible for the "queue" logic and also making it thread-safe.
With the new mixin, queues now use a running flag instead of a
shutdown flag. The biggest difference with this change is that
the default state of a queue is not running or shutdown. This is
more correct, a queue `start` method should be called before using
the …
> Add `Queue` mixin for defining custom queues

- test/support/thread_spies.rb
- test/unit/default_queue_tests.rb
This cleans up the default queue unit tests to use our latest
conventions and test mutex/condition variable behavior. This also
includes more edge case testing with the default queue and threads.
This is to improve the test suite and keep it maintained.
Related to #14
> Cleanup `DefaultQueue` unit tests; add edge case testing

- lib/dat-worker-pool.rb
- test/system/use_worker_pool_tests.rb
- test/unit/dat-worker-pool_tests.rb
This updates `DatWorkerPool` to allow passing a queue to it. This
with the queue mixin will allow using a custom queue with a worker
pool. This will allow specific systems to use their own custom
queue logic and let them still use the worker pool.
A `queue` option can now be passed when initializing a dat worker
pool instance. This will set the queue that the worker pool uses.
If a queue option is not provided it will build the default queue
as it previously did.
Now that a custom queue can be provided, this removes the worker
pool methods that expected the default queue. The worker pool no
longer demeters the queues work items, whether or not its empty or
its callbacks. Custom queues may not provide these methods so the
worker pool can't always expect them.
This also updates some of the …
> Allow passing a queue to a worker pool

- lib/dat-worker-pool/default_queue.rb
- test/unit/default_queue_tests.rb
This updates the `DefaultQueue` callbacks to pass the queue and
work item to them. This makes them consistent with the worker
callbacks and makes them more useful. Now they can use the queue
or work item if needed.
This also fixes a bug with running the on pop callbacks even if
they popped a `nil` work item. Dat worker pool as a whole ignores
`nil` work items and this makes the on pop consistent with that
behavior. The bug this fixes is running on pop callbacks when a
queue is shutdown with a worker thread waiting on pop. Prevously
the worker thread would get a `nil` work item but it would have
caused the on pop callbacks to run.
> Change `DefaultQueue` callbacks, pass the queue and work item

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/default_worker.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/default_worker_tests.rb
This renames the `Worker` class to `DefaultWorker`. This is setup
for having a `Worker` mixin for defining custom worker classes for
dat worker pool. This renames the existing worker as a first step
so the `Worker` name is now available.
> Rename `Worker` to `DefaultWorker`, setup for worker mixin

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/default_worker.rb
- lib/dat-worker-pool/runner.rb
- lib/dat-worker-pool/worker.rb
- test/support/thread_spies.rb
- test/system/use_worker_pool_tests.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/default_worker_tests.rb
- test/unit/runner_tests.rb
- test/unit/worker_tests.rb
This adds a `Runner` class and `Worker` mixin. This is part of an 
effort to allow providing a custom worker class and in general make 
dat worker pool more flexible and powerful.
This adds a `Runner` which is built by a worker pool and passed
to a worker. This is so we can remove the default worker callbacks
that the worker pool added to its workers for despawning workers
and incrementing/decrementing waiting worker counts. Instead of
using the callbacks and relying on ruby's closures to allow
calling private methods on the worker pool, the worker now
directly calls the runner. When the worker sleeps/wakes up it
calls a public increment/decrement method on the runner. When
it shuts down it calls the public despawn worker method on the
runner. The runner allows methods that are intended …
> Add `Runner` class and `Worker` mixin

- lib/dat-worker-pool/default_worker.rb
- lib/dat-worker-pool/worker.rb
- test/unit/default_worker_tests.rb
- test/unit/worker_tests.rb
This adds the rest of the logic from `DefaultWorker` to the
`Worker` mixin. This fills out the worker with all the logic
needed to define custom workers.
The `Worker` mixin now contains all the logic needed to define
custom workers. It knows how to start, shutdown and process work
items while running. Most of the logic was copied straight out of
the default worker but a few things were changed:
* The mixin now expects a `work!` method to be defined. This is
tells it how to process a work item. It doesn't accept an on
work proc.
* Switch from a shutdown flag to a running flag. This is consistent
with queues and makes the default state of the worker not running
(shutdown).
* This changes the `running?` method to be based on the running
flag instead of if the thread is alive. This is for …
> Add the rest of the `Worker` logic from `DefaultWorker`

- lib/dat-worker-pool/runner.rb
- lib/dat-worker-pool/worker.rb
- test/system/use_worker_pool_tests.rb
- test/unit/runner_tests.rb
- test/unit/worker_tests.rb
This changes the worker callbacks to be instance exec'd, wraps
the on-start and on-shutdown in begin-rescues and changes the
worker to spawn itself with the runner when its started. This is
to make the callbacks more consistent and safer (keep them from
messing up the worker behavior).
The worker callbacks are now instance exec'd instead of being
called. This makes them more consistent with the `work!` method
and lets them easily access the queue and params.  As part of this,
the internal methods and ivars for the workers behavior have been
namespaced to avoid user defined methods and ivars.
This also wraps the on-start and on-shutdown callbacks in
begin-rescues. This is to ensure that if they raise an error, the
on-error callbacks get called. This also tries to keep the errors
from …
> Change worker callbacks, instance exec and begin-rescue them

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/queue.rb
- lib/dat-worker-pool/runner.rb
- lib/dat-worker-pool/worker.rb
- test/system/use_worker_pool_tests.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/queue_tests.rb
- test/unit/runner_tests.rb
- test/unit/worker_tests.rb
This is a number of small changes to the shutdown logic. In general
these are related to error handling when shutting down. Now that
its possible for queues and workers to be customized its possible
for more errors to be introduced. This ensures we cover those
scenarios and try to report the errors as much as possible.
* The workers and queue are now signalled to shutdown outside the
timeout so they will always be "shutdown" even if the timeout is
short.
* Runner shutdown will now rescue errors when joining workers and
if an error occurs it will manually remove it. This ensures that if
a worker errors it doesn't get the other workers killed when they
could shutdown normally.
* Runner shutdown will now catch standard errors that are thrown
and do a forced shutdown. This avoids the process …
> Changes to shutdown logic

- lib/dat-worker-pool/worker.rb
- lib/dat-worker-pool/worker_pool_spy.rb
- test/unit/worker_pool_spy_tests.rb
- test/unit/worker_tests.rb
This updates the worker pool spy with all the changes that were
made to the worker pool. This also adds worker test helpers for
help testing custom workers.
The worker pool spy is a test helper that can be stubbed in as a
replacement to a real worker pool. This updates it so it continues
to provide the same interface as a real worker pool. This keeps it
relevant and useful as a test helper.
This also adds worker test helpers that help with building a worker
and running its behavior. The test runner it builds can be used to
run the workers callbacks and work method separately or all
together. This should help with testing custom worker logic and
making sure it works as expected.
> Update `WorkerPoolSpy` and add `Worker::TestHelpers`

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/runner.rb
- lib/dat-worker-pool/worker.rb
- lib/dat-worker-pool/worker_pool_spy.rb
- test/system/use_worker_pool_tests.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/runner_tests.rb
- test/unit/worker_tests.rb
This switches workers from having sleep and wakeup callbacks to
having unavailable and available callbacks. This also switches
from counting the number of waiting workers to a set of available
workers. The goal of this is to be more accurate about the workers
behavior and make it easier to understand when callbacks will
be called.
The workers previous sleep and wakeup callbacks were not always
accurate. It's not possible for the worker to tell if it will
actually go to sleep and wakeup. This switches out the inaccuracy
of those callbacks for worker unavailable/available logic. This
happens when it starts working (it becomes unavailable) and
once it finished working (it becomes available). This is accurate
and less confusing than the previous sleep and wakeup callbacks.
As part of adding …
> Switch from sleep/wakeup to unavailable/available callbacks

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/queue.rb
- lib/dat-worker-pool/runner.rb
- lib/dat-worker-pool/worker.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/default_queue_tests.rb
- test/unit/queue_tests.rb
- test/unit/runner_tests.rb
- test/unit/worker_tests.rb
This namespaces the internal `Queue` methods and ivars. This is to
avoid user-defined methods and ivars accidentally overwriting queue
behavior. This is also consistent with the worker, where
user-defined methods and ivars were also namespaced for the same
reasons.
> Namespace `Queue` methods

- lib/dat-worker-pool/default_queue.rb
- lib/dat-worker-pool/locked_object.rb
- lib/dat-worker-pool/runner.rb
- test/system/use_worker_pool_tests.rb
- test/unit/default_queue_tests.rb
- test/unit/locked_object_tests.rb
- test/unit/runner_tests.rb
This adds `LockedObject`, `LockedArray` and `LockedSet` utility
classes which commonizes an object and mutex being used together.
The mutex is used to lock interactions which the object so it makes
sure only one thread is operating on it at a time. This was already
being done through most of dat-worker-pool, this just formalizes it
and also provides it as a helper for other gems that use
dat-worker-pool.
This adds a base `LockedObject` class which takes a value and
builds a mutex for it. The mutex is used to lock access to the
value. The base `LockedObject` only provides a method for reading
the value, a method for setting it and a helper for accessing the
value with the lock. This is used as the base for the `LockedArray`
and `LockedSet` class.
The `LockedArray` class takes an array and …
> Add `LockedObject`, `LockedArray` and `LockedSet` utility classes

- Gemfile
- dat-worker-pool.gemspec
- lib/dat-worker-pool/locked_object.rb
- test/system/dat-worker-pool_tests.rb
- test/unit/locked_object_tests.rb
This reworks the system tests to be more maintanable, match our
latest conventions and faster.
The tests no longer rely on sleeping or "polling" to achieve
certain scenarios. Instead they use mutexes and condition variables
to ensure certain scenarios are setup. These allow the workers and
test suite thread to signal one another and ensure the workers are
in a specific state before we make an assertion.
This also switches the tests to use randomized data as much as
possible which ensures we don't have magic values that conveniently
make the tests pass.
Finally, this adds a `size` method to the `LockedArray` which is
used by the new system tests.
@kellyredding - Ready for review. The diff is probably not very useful, its a rewrite. The concepts of the old tests are preserved but all the …
> Rework system tests

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/worker_pool_spy.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/worker_pool_spy_tests.rb
This alias' the dat-worker-pool `add_work` as `push`. This matches
the queue `push` method and allows staying with the "push" and
"pop" wording if desired.
> Alias `add_work` as `push`

- test/helper.rb
- test/support/thread_spies.rb
- test/system/dat-worker-pool_tests.rb
- test/unit/default_queue_tests.rb
- test/unit/worker_tests.rb
This updates the workers used in the worker tests to signal their
test suite thread as they move into different states. This makes
the test less fragile and ensures the worker has reached the state
we expect before try and make any assertions. This mimics changes
that were done to the dat-worker-pool system tests to make them
less fragile.
Specifically, this fixes an issue when logging is added to the
workers. This slows down the workers and causes ruby to switch to
other threads. This means it can switch to the test suite thread
and make assertions before the worker has had a chance to do
anything. This causes tests to fail even though they shouldn't if
the worker thread has a chance to run.
This also includes some cleanups to the tests to try and
commonize as much of their setup as …
> Update workers to signal their test suite thread in worker tests

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/queue.rb
- lib/dat-worker-pool/worker_pool_spy.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/queue_tests.rb
- test/unit/worker_pool_spy_tests.rb
This updates `DatWorkerPool` and `Queue` to have `work_items`
methods and updates the `WorkerPoolSpy` to use its queue for its
work items. This makes using the default queue with a worker pool
simpler and makes the worker pool spy match the real worker pool
more making it a better spy.
Gems (specifically, dat-tcp) need to read the current work items
on the worker pool's default queue. Without a `work_items` method
on the worker pool they have to manually build a default queue
and pass that into the worker pool. This makes it more annoying to
use a default queue. Ideally, if you want to use the default queue
you never need to pass it into the worker pool.
To allow `DatWorkerPool` to provide a `work_items` method the
`Queue` mixin now provides it by default but it raises a not
implemented …
> Add `work_items` to pool and queue, make pool spy use queue

- lib/dat-worker-pool.rb
- lib/dat-worker-pool/runner.rb
- lib/dat-worker-pool/worker.rb
- test/helper.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/runner_tests.rb
- test/unit/worker_pool_spy_tests.rb
- test/unit/worker_tests.rb
This updates the runner and workers to have debug logging. This is
to help with seeing what a worker pool and its workers are doing.
The runner will now log when it starts and shuts down. It logs the
number of workers it is starting or waiting to shut down and will
log if it is doing a normal shutdown or forcing the workers to
shutdown.
The worker will log as it moves between its different states:
starting, available, unavailable, working and shutting down. It
also logs any errors that occur.
In addition to adding logging, workers are now given a number by
their runner. This is used in their logs to identify the worker
and is also a helper that can be used in custom logging or other
logic as needed.
> Add logging to runner and workers

- dat-worker-pool.gemspec
- lib/dat-worker-pool.rb
- lib/dat-worker-pool/runner.rb
- test/system/dat-worker-pool_tests.rb
- test/unit/dat-worker-pool_tests.rb
- test/unit/runner_tests.rb
- test/unit/worker_tests.rb
This is part of getting this working in modern ruby versions.
SystemTimer isn't compatible.  This switches to using our new
much-timeout gem for handling timeouts.
There are a couple of minor tweaks related to this change:
* MuchTimeout has a `just_optional_timeout` method that not only
takes care of optionally applying the timeout but also removes
any exception being raised when a timeout occurs.
* The previous shutdown logic attempted to abstract the dwp
internals in the shutdown error backtraces by accepting a custom
caller to use as the backtrace.  This proved to be less helpful
b/c you never get to see where in the worker the shutdown error
occurred.  This removes all the custom backtrace logic.
* this fixes a test now that timeouts of zero immediately interrupt
(this wasn't the case …
> replace SystemTimer with MuchTimeout

- test/support/signal_test_worker.rb
- test/system/dat-worker-pool_tests.rb
- test/unit/default_queue_tests.rb
- test/unit/runner_tests.rb
- test/unit/worker_tests.rb
This updates the test suite to work with newer versions of ruby.
This mostly involved doing more "hand-holding" to ensure threads
were given a chance to run or to reach a certain state before any
assertions were done. This gets all the tests passing in newer
versions of ruby and in ruby 1.8.7.
This fixes the default queue unit tests by simply adding some extra
thread joins to ensure it gets a chance to run. This allows it to
reach the expected state before any assertions happen.
This fixes the runner unit tests by making a few changes:
* The workers now signal when they become available and
unavailable. This allows the tests to ensure the workers have
reached an expected state before running any assertions. This
logic was commonized from the system tests so both sets of tests
can make use …
> Update test suite to work with newer versions of ruby

- lib/dat-worker-pool/worker.rb
- test/system/dat-worker-pool_tests.rb
- test/unit/worker_tests.rb
This updates the `Worker` to rescue `Timeout::Error` and treat it
as a standard error. This is to fix an issue where timeout errors
were causing worker threads to shutdown. This is because timeout
errors don't inherit from `StandardError` so they wouldn't be
caught and the worker's work loop would exit. Timeout errors are
now rescued with standard errors. This means they will run through
the error callbacks for the worker and then be ignored which keeps
the work loop from exiting.
> Rescue `Timeout::Error` in `Worker` and handle like a standard error
